name: gql_codegen
description: Generator for Graphql Files
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_style: ">=2.0.0 <3.0.0"
  code_builder: ">=4.0.0 <5.0.0"
  gql: ^0.13.0
  build: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.0.4
  build_runner: ^2.4.6
  test: ^1.24.3
