name: gql_codegen
description: Generator for Graphql Files
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  # Graphql Code Generator Dependencies
  dart_style: ">=2.0.0 <3.0.0"
  code_builder: ">=4.0.0 <5.0.0"
  source_gen: ^1.0.2
  args: ">=2.0.0 <3.0.0"
  gql: ^0.13.0
  glob:
  build: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.0.4
  build_runner: ^2.0.4
